 language: node_js
 node_js:
   - 10.15.3

 jobs:
   include:
     - stage: build
       name: "Build"
       if: branch = master OR branch = /greenkeeper\/.*/
       script: yarn
       script: npx framer-cli build <your-project-path.framerfx>

     - stage: publish
       name: "Publish"
       if: branch = master OR branch = /greenkeeper\/.*/
       script: yarn
       script: npx framer-cli publish <your-project-path.framerfx> --yes